app:
  name: LearningSpringBoot
  description: ${app.name} is a Spring Boot application
server:
  port: 8080
logging:
  level:
    com:
      ndamelio:
        learning:
          springboot: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    beans:
      enabled: true
    health:
      show-details: always
  info:
    git:
      mode: full
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true
    env:
      enabled: true
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-comments
          group: learning-spring-boot
        output:
          destination: learning-spring-boot-comments
          group: learning-spring-boot