app:
  name: LearningSpringBoot
  description: ${app.name} is a Spring Boot application
server:
  port: 8080
logging:
  level:
    reactor:
      core: TRACE
      util: TRACE
    com:
      ndamelio:
        learning:
          springboot: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true